running=OS_STDOUT_CAPTURE=${OS_STDOUT_CAPTURE:-1} \
OS_STDERR_CAPTURE=${OS_STDERR_CAPTURE:-1} \
OS_TEST_TIMEOUT=${OS_TEST_TIMEOUT:-500} \
OS_TEST_LOCK_PATH=${OS_TEST_LOCK_PATH:-${TMPDIR:-'/tmp'}} \
${PYTHON:-python} -m subunit.run discover -t ./ ${OS_TEST_PATH:-./tempest/test_discover} --list 
running=OS_STDOUT_CAPTURE=${OS_STDOUT_CAPTURE:-1} \
OS_STDERR_CAPTURE=${OS_STDERR_CAPTURE:-1} \
OS_TEST_TIMEOUT=${OS_TEST_TIMEOUT:-500} \
OS_TEST_LOCK_PATH=${OS_TEST_LOCK_PATH:-${TMPDIR:-'/tmp'}} \
${PYTHON:-python} -m subunit.run discover -t ./ ${OS_TEST_PATH:-./tempest/test_discover}  --load-list /tmp/tmpue989h
======================================================================
FAIL: tempest.api.object_storage.test_container_services.ContainerTest.test_list_container_contents_with_end_marker[gate,smoke]
tags: worker-0
----------------------------------------------------------------------
Empty attachments:
  pythonlogging:''
  stderr
  stdout

Traceback (most recent call last):
  File "/work/tempest/tempest/api/object_storage/test_container_services.py", line 194, in test_list_container_contents_with_end_marker
    self.assertEqual(object_name, object_list.strip('\n'))
  File "/home/adam/.local/lib/python2.7/site-packages/testtools/testcase.py", line 350, in assertEqual
    self.assertThat(observed, matcher, message)
  File "/home/adam/.local/lib/python2.7/site-packages/testtools/testcase.py", line 435, in assertThat
    raise mismatch_error
testtools.matchers._impl.MismatchError: 'TestObject-1221631230' != ''
======================================================================
FAIL: tempest.api.object_storage.test_container_sync_middleware.ContainerSyncMiddlewareTest.test_container_synchronization[slow]
tags: worker-0
----------------------------------------------------------------------
Empty attachments:
  pythonlogging:''
  stderr
  stdout

Traceback (most recent call last):
  File "/work/tempest/tempest/test.py", line 154, in wrapper
    return func(*func_args, **func_kwargs)
  File "/work/tempest/tempest/api/object_storage/test_container_sync_middleware.py", line 51, in test_container_synchronization
    self._test_container_synchronization(make_headers)
  File "/work/tempest/tempest/api/object_storage/test_container_sync.py", line 106, in _test_container_synchronization
    'Different object lists in containers.')
  File "/home/adam/.local/lib/python2.7/site-packages/testtools/testcase.py", line 350, in assertEqual
    self.assertThat(observed, matcher, message)
  File "/home/adam/.local/lib/python2.7/site-packages/testtools/testcase.py", line 435, in assertThat
    raise mismatch_error
testtools.matchers._impl.MismatchError: !=:
reference = {u'TestSyncObject-44504475': {u'bytes': 23,
                              u'content_type': u'application/json',
                              u'hash': u'fe417bdeebbed56e718a2a383ae4e418',
                              u'last_modified': u'2017-06-12T11:11:08.465Z',
                              u'name': u'TestSyncObject-44504475'}}
actual    = {}
: Different object lists in containers.
======================================================================
FAIL: process-returncode
tags: worker-0
----------------------------------------------------------------------
Binary content:
  traceback (test/plain; charset="utf8")
Ran 131 tests in 74.138s (+9.177s)
FAILED (id=1017, failures=3, skips=3)
