running=OS_STDOUT_CAPTURE=${OS_STDOUT_CAPTURE:-1} \
OS_STDERR_CAPTURE=${OS_STDERR_CAPTURE:-1} \
OS_TEST_TIMEOUT=${OS_TEST_TIMEOUT:-500} \
OS_TEST_LOCK_PATH=${OS_TEST_LOCK_PATH:-${TMPDIR:-'/tmp'}} \
${PYTHON:-python} -m subunit.run discover -t ./ ${OS_TEST_PATH:-./tempest/test_discover} --list 
running=OS_STDOUT_CAPTURE=${OS_STDOUT_CAPTURE:-1} \
OS_STDERR_CAPTURE=${OS_STDERR_CAPTURE:-1} \
OS_TEST_TIMEOUT=${OS_TEST_TIMEOUT:-500} \
OS_TEST_LOCK_PATH=${OS_TEST_LOCK_PATH:-${TMPDIR:-'/tmp'}} \
${PYTHON:-python} -m subunit.run discover -t ./ ${OS_TEST_PATH:-./tempest/test_discover}  --load-list /tmp/tmpAXGoh_
======================================================================
FAIL: tempest.api.object_storage.test_container_services.ContainerTest.test_list_container_contents_with_end_marker[gate,smoke]
tags: worker-0
----------------------------------------------------------------------
Empty attachments:
  pythonlogging:''
  stderr
  stdout

Traceback (most recent call last):
  File "/work/tempest/tempest/api/object_storage/test_container_services.py", line 194, in test_list_container_contents_with_end_marker
    self.assertEqual(object_name, object_list.strip('\n'))
  File "/home/adam/.local/lib/python2.7/site-packages/testtools/testcase.py", line 350, in assertEqual
    self.assertThat(observed, matcher, message)
  File "/home/adam/.local/lib/python2.7/site-packages/testtools/testcase.py", line 435, in assertThat
    raise mismatch_error
testtools.matchers._impl.MismatchError: 'TestObject-910255234' != ''
======================================================================
FAIL: tempest.api.object_storage.test_container_sync_middleware.ContainerSyncMiddlewareTest.test_container_synchronization[slow]
tags: worker-0
----------------------------------------------------------------------
Empty attachments:
  pythonlogging:''
  stderr
  stdout

Traceback (most recent call last):
  File "/work/tempest/tempest/test.py", line 154, in wrapper
    return func(*func_args, **func_kwargs)
  File "/work/tempest/tempest/api/object_storage/test_container_sync_middleware.py", line 51, in test_container_synchronization
    self._test_container_synchronization(make_headers)
  File "/work/tempest/tempest/api/object_storage/test_container_sync.py", line 106, in _test_container_synchronization
    'Different object lists in containers.')
  File "/home/adam/.local/lib/python2.7/site-packages/testtools/testcase.py", line 350, in assertEqual
    self.assertThat(observed, matcher, message)
  File "/home/adam/.local/lib/python2.7/site-packages/testtools/testcase.py", line 435, in assertThat
    raise mismatch_error
testtools.matchers._impl.MismatchError: !=:
reference = {u'TestSyncObject-321195462': {u'bytes': 24,
                               u'content_type': u'application/json',
                               u'hash': u'ba93d60b1c01d5bb5967548c41fa2376',
                               u'last_modified': u'2017-06-12T11:23:24.295Z',
                               u'name': u'TestSyncObject-321195462'}}
actual    = {}
: Different object lists in containers.
======================================================================
FAIL: process-returncode
tags: worker-0
----------------------------------------------------------------------
Binary content:
  traceback (test/plain; charset="utf8")
Ran 131 (+129) tests in 76.479s (+76.192s)
FAILED (id=1021, failures=3 (+1), skips=3)
